# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "ray-77-tf-state"
    dynamodb_table = "my-lock-table"
    encrypt        = true
    key            = "ec2/terraform.tfstate"
    region         = "ap-southeast-1"
  }
}
