# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    key            = "app/terraform.tfstate"
    region         = "ap-southeast-1"
    bucket         = "ray-77-tf-state"
    dynamodb_table = "my-lock-table"
    encrypt        = true
  }
}
