# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    region         = "ap-southeast-1"
    bucket         = "ray-77-tf-state"
    dynamodb_table = "my-lock-table"
    encrypt        = true
    key            = "frontend-app/terraform.tfstate"
  }
}
