# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    region         = "ap-southeast-1"
    bucket         = "ray-staging-tf-state"
    dynamodb_table = "ray-staging-tf-state"
    encrypt        = true
    key            = "sqs/terraform.tfstate"
  }
}
