# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    key            = "vpc/terraform.tfstate"
    region         = "ap-southeast-1"
    bucket         = "ray-production-tf-state"
    dynamodb_table = "ray-production-tf-state"
    encrypt        = true
  }
}
